name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Import GPG Key
        uses: crazy-max/ghaction-import-gpg@v6
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PASSPHRASE }}
#       - name: Set up JDK 1.8
#         uses: actions/setup-java@v4
#         with:
#           distribution: 'temurin'
#           java-version: 8
#           cache: 'maven'
#
#       - name: Set up Aerospike Database
#         uses: reugn/github-action-aerospike@v1
#
#       - name: Build with Maven
#         run: mvn clean test -B -U

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          server-id: ossrh
          server-username: ${{ secrets.OSSRH_USERNAME }}
          server-password: ${{ secrets.OSSRH_PASSWORD }}
          gpg-private-key: ${{ secrets.GPG_PRIVATE_KEY }}
          gpg-passphrase:  ${{ secrets.GPG_PASSPHRASE }}

#       - name: Publish package
#         run: mvn --batch-mode -DskipTests deploy
#         env:
#           MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#           MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
#


      - name: Publish package
        run: mvn clean deploy -Dgpg.passphrase=${{ secrets.GPG_PASSPHRASE }} -DskipTests
#         env:
#           MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
#           MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}


#
#       - name: Publish package
#         run: mvn --batch-mode -DskipTests deploy
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}