name: Build
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

#       - name: Set up JDK 1.8
#         uses: actions/setup-java@v4
#         with:
#           distribution: 'temurin'
#           java-version: 8
#           cache: 'maven'
#
#       - name: Set up Aerospike Database
#         uses: reugn/github-action-aerospike@v1
#
#       - name: Build with Maven
#         run: mvn clean test -B -U

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 21
          server-id: ossrh
          server-username: ${{ secrets.MAVEN_USERNAME}}
          server-password: ${{ secrets.MAVEN_PASSWORD }}
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}

#
#       - name: Publish package
#         run: mvn --batch-mode -DskipTests deploy
#         env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}